<?php

use Avarda\HyvaAvardaPaymentCompatible\Model\Magewire\Checkout\Payment\Method\AvardaPayments;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var AvardaPayments $magewire */
/** @var Escaper $escaper */

?>
<div class="col-span-6">
    <div class="block font-medium text-gray-700">
        <span class="text-gray-500 font-medium text-sm">
            <?php
            // Get the method from last part of layout name
            $parts = explode('.', $block->getNameInLayout());
            $method = end($parts);
            echo $magewire->getTermsHtml($method);
            ?>
        </span>
    </div>
    <br>
    <label class="block font-medium text-gray-700">
        <?= $escaper->escapeHtml(__('Social Security Number')) ?>
        <input wire:model.lazy="socialSecurityNumber"
               type="text" class="block w-full shadow-sm border-gray-300 rounded-md"
        />
    </label>
    <br>
    <?php if ($magewire->hasError('socialSecurityNumber')): ?>
        <p class="text-red-500 mt-4 text-sm">
            <?= $escaper->escapeHtml($magewire->getError('socialSecurityNumber')) ?>
        </p>
    <?php endif ?>
</div>
